---
title: "Longitudinal Single-Level Regression"
format:
  live-html:
    css: 
      - exams/webex.css
    include-after-body: exams/webex.js
webr:
  packages:
    - dplyr
    - ggplot2
    - haven
toc: true    
---

{{< include _extensions/r-wasm/live/_knitr.qmd >}}


## Grundidee
Mehrebenenregressionsmodelle (auch Multi-Level-Modelle, Hierachische Modelle oder Mixed-Effects-Modelle) sind ein mächtiges Werkzeug zur Modellierung von Daten, die auf mehreren Ebenen genested (geclusterd) organisiert sind. Diese Cluster können etwa Schülerinnen und Schüler in Klassen sein oder Messwiederholungen in Merkmalsträgern. 
Die Grundidee der Modellierung längsschnittlicher Daten mit Mehrebenenmodellen besteht darin, sowohl die Variation innerhalb der Cluster (=Merkmalsträger) als auch zwischen den Clustern zu modellieren. Die Variation zischen den Clustern (auch Level-2 Effekte oder Random Effekte) werden dabei als »Streuung von Regressionsparametern« konzeptualisiert.



## Prädiktion von Differenzwerten {#sec-prädiktion-differenzen}
```{r}
library(haven)
library(dplyr)
library(ggplot2)


data_star <- read_sav(
  "https://raw.githubusercontent.com/sammerk/WinterSchoolZH/master/data_star_workshop.sav"
)

data_star_subset <- data_star %>%
  group_by(g2tchid) %>%
  summarize(
    MathClassMeanCl2 = mean(g2tmathss, na.rm = T),
    MathClassMeanCl3 = mean(g3tmathss, na.rm = T),
    MathClassMeanCl4 = mean(g4tmathss, na.rm = T),
    PropFreeLunchCl2 = mean(ifelse(g2freelunch == 1, 1, 0), na.rm = T),
    PropFreeLunchCl3 = mean(ifelse(g3freelunch == 1, 1, 0), na.rm = T),
    PropFreeLunchCl4 = mean(ifelse(g4freelunch == 1, 1, 0), na.rm = T),
    g2classsize = mean(g2classsize, na.rm = T),
    g3classsize = mean(g3classsize, na.rm = T),
    g4classsize = mean(g4classsize, na.rm = T)
  ) %>%
  ungroup() %>%
  # Berechnung des Veränderungsscores
  mutate(
    `Mathe Klassenmittelwert Veränderung` = `Mathe Klassenmittelwert Kl. 3` -
      `Mathe Klassenmittelwert Kl. 2`
  )
```


### Grafische Darstellung
```{webr}
#| envir: myenv
#| exercise: plot diff prediction
#| autorun: false
#| warning:	false

ggplot(
  data_star_subset,
  aes(x = g3classsize, y = `Mathe Klassenmittelwert Veränderung`)
) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Veränderung des Mathe Klassenmittelwerts nach Klassenstärke",
    x = "Klassenstärke (Kl. 3)",
    y = "Veränderung des Mathe Klassenmittelwerts"
  ) +
  theme_minimal()

```


### Prädiktion der Differenz mit `g3classsize`

```{webr}
#| envir: myenv
#| exercise: model diff prediction
#| autorun: false
#| warning:	false

mod_change_linreg01 <- lm(
  `Mathe Klassenmittelwert Veränderung` ~ + g3classsize,
  data = data_star_subset
)

summary(mod_change_linreg01)
```

## Prädiktion nach Adjustierung um Prä-Messung {#sec-prädiktion-nach-adjustierung}
### Grafische Darstellung

```{webr}
#| envir: myenv
#| exercise: plot adjusted prediction
#| autorun: false
#| warning:	false

ggplot(
  data_star_subset,
  aes(
    x = `Mathe Klassenmittelwert Kl. 2`,
    y = `Mathe Klassenmittelwert Kl. 3`,
    color = g3classsize
  )
) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Mathe Klassenmittelwerte Kl. 2 vs. Kl. 3",
    x = "Mathe Klassenmittelwert Kl. 2",
    y = "Mathe Klassenmittelwert Kl. 3"
  ) +
  theme_minimal()
```

### Prädiktion nach Adjustierung
```{webr}
#| envir: myenv
#| exercise: model adjusted prediction
#| autorun: false
#| warning:	false

mod_change_linreg02 <- lm(
  `Mathe Klassenmittelwert Kl. 3` ~ `Mathe Klassenmittelwert Kl. 2` + g3classsize,
  data = data_star_subset
)

summary(mod_change_linreg02)
```

