---
title: "Longitudinal Single Level Regression"
format:
  live-html:
    css: 
      - exams/webex.css
    include-after-body: exams/webex.js
webr:
  packages:
    - dplyr
    - ggplot2
    - haven
toc: true    
---

{{< include _extensions/r-wasm/live/_knitr.qmd >}}

Die multiple Regression ist bereits ein mächtiges Werkzeug zur Modellierung längsschnittlicher Daten, wenn nicht mehr als zwei Messzeitpunkte vorliegen.

## Grundidee
Wird eine Messung genau einmal wiederholt (z.B. Variablen $AV_{PRE}$, $AV_{POST}$), so kann in einem Single-Level Regressionsmodell 

* die Differenz $\left(AV^{POST}_i - AV^{PRE}_i\right)$  (siehe @sec-prädiktion-differenzen) oder 
* die Abweichung des tatsächlichen zweiten Messwertes vom erwarteten zweiten Wert (z.B. Residuum der Regression $AV^{POST}_i = b_0 + b_1 \cdot AV^{PRE}_i + \epsilon_i$ (siehe @sec-prädiktion-nach-adjustierung)

mit weiteren unabhängigen Variablen prädiziert werden.


## Prädiktion von Differenzwerten {#sec-prädiktion-differenzen}
### Datenaufbereitung

```{webr}
#| envir: env chapter single-level
#| exercise: data setup longitudinal single level
#| autorun: false
#| warning:	false

library(haven)
library(dplyr)
library(ggplot2)
data_star <- read_sav(
  "https://raw.githubusercontent.com/sammerk/WinterSchoolZH/master/data_star_workshop.sav"
)

data_star_subset <- data_star %>%
  group_by(g3tchid) %>%
  summarize(
    `Mathe Klassenmittelwert Kl. 2` = mean(g2tmathss, na.rm = T),
    `Mathe Klassenmittelwert Kl. 3` = mean(g3tmathss, na.rm = T),
    `Anteil Free Lunch` = mean(ifelse(g2freelunch == 1, 1, 0), na.rm = T),
    g3classsize = mean(g3classsize, na.rm = T)
  ) %>%
  ungroup() %>%
  # Berechnung des Veränderungsscores
  mutate(
    `Mathe Klassenmittelwert Veränderung` = `Mathe Klassenmittelwert Kl. 3` -
      `Mathe Klassenmittelwert Kl. 2`
  )
```


### Grafische Darstellung
```{webr}
#| envir: env chapter single-level
#| exercise: plot diff prediction
#| autorun: false
#| warning:	false

ggplot(
  data_star_subset,
  aes(x = g3classsize, y = `Mathe Klassenmittelwert Veränderung`)
) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Veränderung des Mathe Klassenmittelwerts nach Klassenstärke",
    x = "Klassenstärke (Kl. 3)",
    y = "Veränderung des Mathe Klassenmittelwerts"
  ) +
  theme_minimal()

```


### Prädiktion der Differenz mit `g3classsize`
Nach einer ersten grafischen Inspektion wollen wir den Veränderungs
```{webr}
#| envir: env chapter single-level
#| exercise: model diff prediction
#| autorun: false
#| warning:	false

mod_change_linreg01 <- lm(
  `Mathe Klassenmittelwert Veränderung` ~ g3classsize,
  data = data_star_subset
)

summary(mod_change_linreg01)
```

## Prädiktion nach Adjustierung um Prä-Messung {#sec-prädiktion-nach-adjustierung}
### Grafische Darstellung

```{webr}
#| envir: env chapter single-level
#| exercise: plot adjusted prediction
#| autorun: false
#| warning:	false

ggplot(
  data_star_subset,
  aes(
    x = `Mathe Klassenmittelwert Kl. 2`,
    y = `Mathe Klassenmittelwert Kl. 3`,
    color = g3classsize
  )
) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Mathe Klassenmittelwerte Kl. 2 vs. Kl. 3",
    x = "Mathe Klassenmittelwert Kl. 2",
    y = "Mathe Klassenmittelwert Kl. 3"
  ) +
  theme_minimal()
```

### Prädiktion nach Adjustierung
```{webr}
#| envir: env chapter single-level
#| exercise: model adjusted prediction
#| autorun: false
#| warning:	false

mod_change_linreg02 <- lm(
  `Mathe Klassenmittelwert Kl. 3` ~ `Mathe Klassenmittelwert Kl. 2` + g3classsize,
  data = data_star_subset
)

summary(mod_change_linreg02)
```

