
```{r, echo=FALSE, results='hide', message=FALSE}
library(tidyverse)
library(exams)
nth_task <- sample(1:6, 1)

data <- tibble(
  Answers_and_Distractors = c(
    "Deskriptive Studie",
    "Explanative Studie",
    "Explorative Studie",
    "Prädiktive Studie"
  ),
  `Die Entwicklung der durchschnittlichen Lesekompetenz einer Kohorte von Schülerinnen und Schülern sowie deren Heterogenität wird über drei Schuljahre hinweg dokumentiert.` = c(
    T,
    F,
    F,
    F
  ),
  `Die Entwicklung der Fehlzeitenquote von Schülerinnen und Schülern wird über vier Schuljahre hinweg erfasst und zusammenfassend beschrieben.` = c(
    T,
    F,
    F,
    F
  ),
  `Über mehrere Messzeitpunkte hinweg wird untersucht, welche elterlichen Unterstützungsformen potenziell mit Veränderungen der schulischen Motivation von Kindern (zeitlich) einhergehen.` = c(
    F,
    F,
    T,
    F
  ),
  `Lernleistungen werden zu mehreren Zeitpunkten erhoben, um zu testen, ob spaced learning langfristig zu besseren Ergebnissen führt als massiertes Lernen` = c(
    F,
    T,
    F,
    F
  ),
  `Es wird untersucht, ob die gleichzeitige Präsentation von Bild und Ton über mehrere Erhebungszeitpunkte hinweg den Wortschatzerwerb in einer Fremdsprache fördert.` = c(
    F,
    T,
    F,
    F
  ),
  `Frühere Leistungsdaten, Motivation und Fehlzeiten werden genutzt, um vorherzusagen, welche Schülerinnen und Schüler im weiteren Verlauf ein erhöhtes Risiko für Leistungsabbrüche zeigen.` = c(
    F,
    F,
    F,
    T
  )
)
  
```


Question
========
### Übung {{< iconify fa7-solid:person-digging >}}{.unnumbered .h3short}
Wird in der folgenden Kurzbeschreibung eine **deskriptive**, **explanative**, **explorative** oder **prädiktive** Studie durchgeführt?

> `r names(data[,nth_task + 1])`

  
```{r questionlist, echo = FALSE, results='asis'}
answerlist(
  data |> pull(1),
  markup = "markdown")
```




Meta-information
================
exname: Erkentnisinteresse in Forschungsfrage erkennen
extype: schoice
exsolution: `r mchoice2string(data |> pull(nth_task + 1))`